/**
 * ONE stylesheet for all three brands.
 * Every rule is written against contract variables only — never a hex literal.
 * Scoping by [data-brand] is what lets one page show all three at once.
 */
const { toCssVars } = require('./contract');

function buildCss(brands) {
  const scopes = brands.map((b) => `[data-brand="${b.id}"] {\n${toCssVars(b)}\n}`).join('\n\n');

  return `/* generated by constellation/build.js — do not edit */
${scopes}

*, *::before, *::after { box-sizing: border-box; }
body { margin: 0; background: var(--c-bg); color: var(--c-text-primary); font-family: var(--c-font-sans); -webkit-font-smoothing: antialiased; }
a { color: inherit; }

.c-shell { max-width: 1180px; margin: 0 auto; padding: 0 var(--c-space-6); }
.c-row { display: flex; flex-wrap: wrap; gap: var(--c-space-3); align-items: center; }
.c-grid-3 { display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: var(--c-space-4); }

.c-label {
  font-family: var(--c-font-mono); font-size: 11px; color: var(--c-text-secondary);
  text-transform: var(--c-label-case); letter-spacing: var(--c-label-tracking);
}

/* ---- atoms ---- */
.c-btn {
  font-family: var(--c-font-sans); font-size: 14px; font-weight: 600; cursor: pointer;
  padding: calc(var(--c-space-3)) calc(var(--c-space-4) * 1.2);
  border-radius: var(--c-radius-md); border: 1px solid var(--c-border);
  background: var(--c-surface); color: var(--c-text-primary);
  transition: transform var(--c-dur) var(--c-ease), box-shadow var(--c-dur) var(--c-ease), background var(--c-dur) var(--c-ease);
}
.c-btn:hover:not(:disabled) { transform: translateY(var(--c-lift)); }
.c-btn:disabled { opacity: .4; cursor: not-allowed; }
.c-btn-primary { background: var(--c-primary); border-color: var(--c-primary); color: var(--c-bg); }
.c-btn-primary:hover:not(:disabled) { box-shadow: 0 0 calc(24px * var(--c-glow-mult)) var(--c-primary-glow); }
.c-btn-secondary { border-color: var(--c-border-glow); }
.c-btn-ghost { background: transparent; border-color: transparent; color: var(--c-text-secondary); }

.c-badge {
  display: inline-flex; align-items: center; gap: 6px;
  font-family: var(--c-font-mono); font-size: 11px;
  text-transform: var(--c-label-case); letter-spacing: var(--c-label-tracking);
  padding: 4px 10px; border-radius: var(--c-radius-full);
  border: 1px solid var(--c-border); background: var(--c-surface); color: var(--c-text-secondary);
}
.c-badge-accent { color: var(--c-primary); border-color: var(--c-border-glow); box-shadow: 0 0 calc(12px * var(--c-glow-mult)) var(--c-primary-glow); }
.c-dot { width: 7px; height: 7px; border-radius: 50%; display: inline-block; }
.c-dot-ok { background: #10b981; } .c-dot-warn { background: #f59e0b; } .c-dot-err { background: #ef4444; }

.c-swatches { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: var(--c-space-3); }
.c-swatch { display: flex; gap: var(--c-space-3); align-items: center; padding: var(--c-space-3);
  border: 1px solid var(--c-border); border-radius: var(--c-radius-md); background: var(--c-surface); }
.c-swatch-chip { width: 38px; height: 38px; border-radius: var(--c-radius-sm); border: 1px solid var(--c-border); flex: none; }
.c-swatch-meta { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
.c-swatch-meta strong { font-size: 12px; }
.c-swatch-meta code { font-family: var(--c-font-mono); font-size: 11px; color: var(--c-text-secondary); }

/* ---- molecules / organisms ---- */
.c-card {
  background: var(--c-surface); border: 1px solid var(--c-border);
  border-radius: var(--c-radius-lg); padding: var(--c-space-6);
  transition: transform var(--c-dur) var(--c-ease), border-color var(--c-dur) var(--c-ease), box-shadow var(--c-dur) var(--c-ease);
}
.c-card:hover { transform: translateY(var(--c-lift)); border-color: var(--c-border-glow); box-shadow: 0 0 calc(28px * var(--c-glow-mult)) var(--c-primary-glow); }
.c-metric { display: flex; flex-direction: column; gap: var(--c-space-2); }
.c-metric-value { font-family: var(--c-font-mono); font-size: 30px; font-weight: 700; }
.c-metric-delta { font-family: var(--c-font-mono); font-size: 12px; color: var(--c-primary); }
.c-feature h4 { margin: var(--c-space-3) 0 var(--c-space-2); font-family: var(--c-font-display); font-size: 19px; }
.c-feature p { margin: 0; color: var(--c-text-secondary); font-size: 14px; line-height: 1.6; }
.c-feature-num { font-family: var(--c-font-mono); font-size: 12px; color: var(--c-primary); letter-spacing: var(--c-label-tracking); }

.c-hero { padding: var(--c-space-12) 0; display: flex; flex-direction: column; gap: var(--c-space-4); align-items: flex-start; }
.c-hero-title { font-family: var(--c-font-display); font-size: clamp(34px, 5vw, 58px); line-height: 1.05; margin: 0; }
.c-hero-title em { font-style: normal; color: var(--c-primary); text-shadow: 0 0 calc(30px * var(--c-glow-mult)) var(--c-primary-glow); }
.c-hero-sub { margin: 0; max-width: 54ch; color: var(--c-text-secondary); line-height: 1.7; }

/* aetheris-only */
.c-term { border: 1px solid var(--c-border); border-radius: var(--c-radius-md); overflow: hidden; background: var(--c-bg); }
.c-term-bar { display: flex; align-items: center; gap: 6px; padding: 10px 12px; background: var(--c-surface); border-bottom: 1px solid var(--c-border); }
.c-term-bar i { width: 10px; height: 10px; border-radius: 50%; background: var(--c-metallic); opacity: .5; }
.c-term-bar span { margin-left: 8px; font-family: var(--c-font-mono); font-size: 11px; color: var(--c-text-secondary); }
.c-term-body { margin: 0; padding: var(--c-space-4); font-family: var(--c-font-mono); font-size: 13px; line-height: 1.8; }
.c-term-p { color: var(--c-primary); } .c-term-d { color: var(--c-text-secondary); }
.c-caret { animation: c-blink 1s steps(2) infinite; }
@keyframes c-blink { 50% { opacity: 0; } }

/* merlin-only */
.c-crest { display: flex; gap: var(--c-space-6); align-items: center; padding: var(--c-space-8);
  border: 1px solid var(--c-border); border-radius: var(--c-radius-lg); background: var(--c-surface); }
.c-crest-mark { width: 84px; height: 84px; flex: none; display: grid; place-items: center;
  font-family: var(--c-font-display); font-size: 27px; font-weight: 700; letter-spacing: .06em;
  border: 1px solid var(--c-border-glow); border-radius: var(--c-radius-md); color: var(--c-primary);
  box-shadow: inset 0 0 calc(30px * var(--c-glow-mult)) var(--c-primary-glow); }
.c-crest-text h4 { margin: 0 0 var(--c-space-2); font-family: var(--c-font-display); font-size: 24px; }
.c-crest-rule { height: 1px; width: 100%; margin-bottom: var(--c-space-2);
  background: linear-gradient(90deg, var(--c-metallic), transparent); }

/* reborn-only */
.c-roster { display: flex; flex-direction: column; gap: var(--c-space-2); }
.c-roster-row { display: grid; grid-template-columns: 40px 70px 1fr auto; gap: var(--c-space-3); align-items: center;
  padding: var(--c-space-3) var(--c-space-4); background: var(--c-surface);
  border: 1px solid var(--c-border); border-left: 3px solid var(--c-primary); border-radius: var(--c-radius-sm);
  transition: transform var(--c-dur) var(--c-ease); }
.c-roster-row:hover { transform: translateX(6px); }
.c-roster-rank { font-family: var(--c-font-mono); color: var(--c-text-secondary); font-size: 12px; }
.c-roster-tag { font-family: var(--c-font-mono); font-weight: 700; color: var(--c-primary); }
.c-roster-name { font-weight: 600; }

/* ---- style guide chrome ---- */
.c-topbar { position: sticky; top: 0; z-index: 20; backdrop-filter: blur(14px);
  background: color-mix(in srgb, var(--c-bg) 82%, transparent); border-bottom: 1px solid var(--c-border); }
.c-topbar-in { display: flex; align-items: center; gap: var(--c-space-4); padding: var(--c-space-4) 0; }
.c-topbar-in .c-spacer { flex: 1; }
.c-brandmark { font-family: var(--c-font-display); font-weight: 700; font-size: 17px; text-decoration: none; }
.c-switch { display: flex; gap: 4px; padding: 4px; border: 1px solid var(--c-border); border-radius: var(--c-radius-full); }
.c-switch a { font-family: var(--c-font-mono); font-size: 11px; text-decoration: none; padding: 6px 12px;
  border-radius: var(--c-radius-full); color: var(--c-text-secondary); text-transform: var(--c-label-case); letter-spacing: var(--c-label-tracking); }
.c-switch a.on { background: var(--c-primary); color: var(--c-bg); }

.c-sec { padding: var(--c-space-12) 0; border-top: 1px solid var(--c-border); }
.c-sec-head { display: flex; align-items: baseline; gap: var(--c-space-3); margin-bottom: var(--c-space-6); flex-wrap: wrap; }
.c-sec-head h3 { margin: 0; font-family: var(--c-font-display); font-size: 26px; }
.c-sec-head p { margin: 0; flex-basis: 100%; color: var(--c-text-secondary); font-size: 14px; }
.c-stage { padding: var(--c-space-8); border: 1px dashed var(--c-border); border-radius: var(--c-radius-lg); }
.c-lvl { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: var(--c-space-4); }
.c-src { font-family: var(--c-font-mono); font-size: 11px; color: var(--c-text-secondary); }
`;
}

module.exports = { buildCss };
